/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Project name: 🧘‍♀️Bianca
 * Environment: Production
 * Project Id: 861513d3-9aaa-00c6-aa47-2317ade87596
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },
} as const;
