/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Project name: 🧘‍♀️Bianca
 * Environment: Production
 * Project Id: 861513d3-9aaa-00c6-aa47-2317ade87596
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: '3ea00129-ab1b-450d-a148-d74f33956e33',
    name: 'Project manager',
  },
} as const;
