import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Organization } from './Organization';

/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Certification
 * Id: 00611e0a-efaf-46ff-9e81-aa3bd1891957
 * Codename: certification
 */
export type Certification = IContentItem<{
  /**
   * Date Earned (date_time)
   * Required: true
   * Id: b640bb02-46e1-4f30-8f4b-2898b629c193
   * Codename: date_earned
   */
  dateEarned: Elements.DateTimeElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: e44ca727-9bb6-428e-b21e-8792c7e4f453
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Issued By (modular_content)
   * Required: true
   * Id: bebf93a4-56f0-4ef1-9e23-f18eb0408f09
   * Codename: issued_by
   */
  issuedBy: Elements.LinkedItemsElement<Organization>;

  /**
   * Name (text)
   * Required: true
   * Id: 9a47c698-ad47-4299-b2fc-f02f8800a4b3
   * Codename: name
   */
  name: Elements.TextElement;
}>;
