import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Person } from './Person';

/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Contact
 * Id: e4104851-a3e2-4bee-82cd-2b82dfc04ed7
 * Codename: contact
 */
export type Contact = IContentItem<{
  /**
   * Calendly Link (text)
   * Required: false
   * Id: 98734fb6-e2f1-482b-b924-688062c6ff41
   * Codename: calendly_link
   */
  calendlyLink: Elements.TextElement;

  /**
   * Email (text)
   * Required: false
   * Id: 790e8376-a6ff-4efb-9559-9d6806a7b055
   * Codename: email
   */
  email: Elements.TextElement;

  /**
   * Person (modular_content)
   * Required: false
   * Id: e20d6555-b30d-49d9-9088-f9fe28a4f2ac
   * Codename: person
   */
  person: Elements.LinkedItemsElement<Person>;

  /**
   * Phone (text)
   * Required: false
   * Id: a5110a81-49ca-45b6-a59d-3add67a60ff8
   * Codename: phone
   */
  phone: Elements.TextElement;
}>;
