import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Content Block
 * Id: 7cdb3d15-6e8b-4256-aeae-66627a0931fd
 * Codename: content_block
 */
export type ContentBlock = IContentItem<{
  /**
   * Body (rich_text)
   * Required: false
   * Id: cc614d08-feb7-433a-9d03-3f3205b88118
   * Codename: body
   */
  body: Elements.RichTextElement;

  /**
   * Headline (text)
   * Required: false
   * Id: fd2c3fce-1926-4fbf-88ee-26c19a4d916f
   * Codename: headline
   */
  headline: Elements.TextElement;
}>;
