import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Contact } from './Contact';

/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Event
 * Id: aad6af9a-6d54-4e63-931b-607f5bc2e0e7
 * Codename: event
 */
export type Event = IContentItem<{
  /**
   * Contact (modular_content)
   * Required: false
   * Id: d596ec64-4153-465a-8862-3c4f096b87be
   * Codename: contact
   */
  contact: Elements.LinkedItemsElement<Contact>;

  /**
   * Description (rich_text)
   * Required: true
   * Id: 3b7b74e2-876f-48d8-a340-071a060c3bd8
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * End Date (date_time)
   * Required: true
   * Id: 29e62336-235b-4f5a-a26c-fb94c8d07435
   * Codename: end_date
   */
  endDate: Elements.DateTimeElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 0a6d08f6-f55d-41c5-b61c-63ac1620286a
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Maximum Occupancy (number)
   * Required: false
   * Id: 24006848-f463-430c-84ff-2a741d89fdcb
   * Codename: maximum_occupancy
   */
  maximumOccupancy: Elements.NumberElement;

  /**
   * Name (text)
   * Required: true
   * Id: bd58d467-5b91-48ad-b298-26f67e9cadaa
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Start Date (date_time)
   * Required: true
   * Id: 6c3e9c32-f304-4b0d-9b46-5cad3fe84226
   * Codename: start_date
   */
  startDate: Elements.DateTimeElement;
}>;
