import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Contact } from './Contact';
import { type ContentBlock } from './ContentBlock';
import { type Event } from './Event';
import { type Service } from './Service';
import { type Video } from './Video';

/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Page
 * Id: 15f22899-b65b-46d9-a037-eee241aabdbc
 * Codename: page
 */
export type Page = IContentItem<{
  /**
   * Banner (asset)
   * Required: true
   * Id: a67d3a11-a581-4bc7-a780-48eed1d0feb5
   * Codename: banner
   */
  banner: Elements.AssetsElement;

  /**
   * Content (modular_content)
   * Required: false
   * Id: 6667a33b-8ef4-4a2d-98df-09f657cb26c7
   * Codename: content
   */
  content: Elements.LinkedItemsElement<
    Video | Service | ContentBlock | Event | Contact
  >;

  /**
   * Show in navigation (multiple_choice)
   * Required: true
   * Id: b678f21c-cf98-462d-9a91-bcf191e1d639
   * Codename: show_in_navigation
   */
  showInNavigation: Elements.MultipleChoiceElement;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: a5ae556e-fdbe-423d-b0bd-3d5099d3a573
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Title (text)
   * Required: true
   * Id: e3dce93e-d4ef-47d7-ab59-4d6571efdb4a
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL (url_slug)
   * Required: true
   * Id: 6af08ca0-8a0a-42b2-bd72-25404dbd5c88
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}>;
