import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Person
 * Id: 85da5d42-f39f-4bc2-9583-3c1f1a49d228
 * Codename: person
 */
export type Person = IContentItem<{
  /**
   * Bio (rich_text)
   * Required: false
   * Id: d0e4561f-fe52-4e4e-95dd-02bd9f24e127
   * Codename: bio
   */
  bio: Elements.RichTextElement;

  /**
   * First Name (text)
   * Required: true
   * Id: 57513cbd-0bf5-40bf-ac4f-f3045f32f139
   * Codename: first_name
   */
  firstName: Elements.TextElement;

  /**
   * Last Name (text)
   * Required: true
   * Id: af4a9559-da58-415a-b211-6d91297e5d3c
   * Codename: last_name
   */
  lastName: Elements.TextElement;

  /**
   * Photo (asset)
   * Required: false
   * Id: d837a85d-e2b4-4151-b1a3-1464f8552e85
   * Codename: photo
   */
  photo: Elements.AssetsElement;

  /**
   * Title (text)
   * Required: false
   * Id: eed6aa3d-696a-49d6-bd6a-4c80ea3cc3cf
   * Codename: title
   */
  title: Elements.TextElement;
}>;
