import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Person } from './Person';

/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Post
 * Id: 12423a46-42eb-4efe-9556-ba4e56b29b0c
 * Codename: post
 */
export type Post = IContentItem<{
  /**
   * Author (modular_content)
   * Required: true
   * Id: df669d78-1a6b-4721-9adb-b67bdc458fac
   * Codename: author
   */
  author: Elements.LinkedItemsElement<Person>;

  /**
   * Body (rich_text)
   * Required: true
   * Id: 6488d1eb-a975-42dd-bc15-84082b4d9311
   * Codename: body
   */
  body: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: true
   * Id: 51daa882-ad1f-4ee0-99ed-9124080680b4
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Related Posts (modular_content)
   * Required: false
   * Id: e6037a04-af99-4268-864e-5a27193062c1
   * Codename: related_posts
   */
  relatedPosts: Elements.LinkedItemsElement<Post>;

  /**
   * Title (text)
   * Required: true
   * Id: 9190e7f2-ca0d-48a3-90c9-5703620a5f1a
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL (url_slug)
   * Required: true
   * Id: 8ed312e9-9142-47c3-afe2-12dbfd5b60d4
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}>;
