import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Feature } from './Feature';

/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Service
 * Id: 7ea8b19f-a223-41b1-a549-653ab273d46a
 * Codename: service
 */
export type Service = IContentItem<{
  /**
   * Description (rich_text)
   * Required: false
   * Id: 980f572a-13d7-4ead-b8a3-97f2ced7f48d
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Features (modular_content)
   * Required: false
   * Id: 0e98b588-1ac0-4d6e-9abf-7b4e629a6da8
   * Codename: features
   */
  features: Elements.LinkedItemsElement<Feature>;

  /**
   * Name (text)
   * Required: true
   * Id: 782f6e16-52c3-47ed-b5da-983b3b84f225
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Price (number)
   * Required: true
   * Id: a60fd5c4-d6ef-45a5-a4d3-ec1fe5e30f2c
   * Codename: price
   */
  price: Elements.NumberElement;
}>;
